### ISSUE TITLE
error: path must be a string and vs code extension not work

### ISSUE THREAD

**Issue by pak1234** [phonglk/simple-html-template#1]
when I execute:
`E:\Downloads\simple-html-template-master>node ./lib/cli.js ./example/html/`

I'm getting this error:
```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at Object.<anonymous> (E:\Downloads\simple-html-template-master\lib\cli.js:2
:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
```
also the visual studio code extension does not work

My config:
windows 10
node -v -> v6.11.5
npm -v -> 5.5.1
visual studio code 1.17.2

**Comment by phonglk** [comment]
Please help to run as
```./lib/cli.js ./example/html/```
or
```npx sht-cli ./example/html/``` in the package is install as depedency

Thank you for your interest
----
Please use the watch feature of the original instead of vs code extension. Thanks!

**Comment by wong1993** [comment]
Found the solution for VSCode extension.

In the file "extension.js:19":

    const parsedUri = vscode.Uri.parse(uri);
    const systemPath = parsedUri.path;

// systemPath variable gets the value: "/" + path
using substring will solve the problem:

    const parsedUri = vscode.Uri.parse(uri);
    const systemPath = parsedUri.path.substring(1);
